version: "3.8"

services:
    postgres:
        image: postgres:14
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - data:/var/lib/postgresql/data
        networks:
            - shop_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on:
            - postgres
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - shop_network

    redis:
        image: redis
        restart: unless-stopped
        container_name: redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis_data:/data
        command: redis-server --save 20 1 --loglevel warning
        networks:
            - shop_network
    k6:
        image: grafana/k6
        container_name: k6
        volumes:
            - ./k6-scripts:/scripts
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/k6
        networks:
            - shop_network

    influxdb:
        image: influxdb:1.8
        restart: unless-stopped
        container_name: influxdb
        ports:
            - "8086:8086"
        volumes:
            - influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=k6
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        networks:
            - shop_network

    grafana:
        image: grafana/grafana
        restart: unless-stopped
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - influxdb
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        networks:
            - shop_network

volumes:
    data:
    pgadmin_data:
    redis_data:
    grafana_data:
    influxdb_data:

networks:
    shop_network:
